### ISSUE TITLE
Values from non editable columns can't be copied with Ctrl+C

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/dderl#120]
@shamis @zsoltm

**Comment by acautin** [comment]
@c-bik I think something else is the issue, I can copy and paste on read only columns fine, i.e. from all views.

system	Remote Tables
system	indexBig
system	longids
...

**Comment by c-bik** [comment]
@acautin

For example:
```sql
select ckey, cvalue:EXPIRY 
from sbsgui.tpac
where rownum < 1000000
```
The `'$not_a_value'` from `cvalue:EXPIRY` can't be copied

**Comment by acautin** [comment]
maybe something to do with the quotes ?, the arrays of "$not_a_value are copied correctly": 
```
["ipprc","0001000018","ipprcv","0930433587"]	
["ipprc","0001000018","ipprcv","0930433587","ipprcvbr"]	["$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value","$not_a_value"]
```

**Comment by c-bik** [comment]
@acautin not only `'` (single quote) it has something to do with exactly `'$not_a_value'` value, everything else works.

Smallest example reproducing bug:
```sql
select '''$not_a_value'''  from dual
```
Other variations I tried and worked (for example) are:
```sql
select '''$_not_a_value'''  from dual
select '''$nota_value'''  from dual
```
Are there any hard coding in JS?

**Comment by acautin** [comment]
not that I remember but maybe, it needs some debugging of the copy to clipboard function.

**Comment by shamis** [comment]
@acautin, @c-bik it was done in this [commit](https://github.com/K2InformaticsGmbH/dderl/commit/4fac72086d5627b3ac930b9b1a2881a08128b818).

**Comment by acautin** [comment]
who was the idiot ? :smile: 

So was a requirement then cc @stoch

**Comment by c-bik** [comment]
@shamis Have you verified if it works or not?

**Comment by stoch** [comment]
@c-bik  This was a purely practical request, which has its benefits. The resoning goes like this:
'$not_a_value' can only be the result of a functional expression, hence read_only. This means we cannot expect it to ever be pasted into an imem table. We don't want it to be pasted anywhere else neither since it should NOT be a value. But still we need it because we don't want to lie and say it is an empty string. This is only correctly understood in our inner imem circle. It will manually have to be cleared out from all Excel sheets and other documentation for all occurances because nobody would understand it otherwise, quite a nuisance.
Of course, the optimum solution would be to have a DDerl rendering option which renders '$not_a_value' as an empty string if so wanted but it can be confusing if this option stays in permanently and gets forgotten.

**Comment by c-bik** [comment]
@stoch IMHO we should first see if there already exists a behavior defined for situation such as this elsewhere and try to follow that -- for example (also noticeable) a better practice adopted in OSs regarding this is a non-copyable item is also non-selectable! I don't remember seeing something like this anywhere else.
