### ISSUE TITLE
Insecure password can be set through AJAX

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/dderl#306]
[login_change_pswd](https://github.com/K2InformaticsGmbH/dderl/blob/master/src/dderl_session.erl#L254-L279)
[change_conn_pswd](https://github.com/K2InformaticsGmbH/dderl/blob/master/src/imem_adapter.erl#L271-L303)

**Comment by stoch** [comment]
This is not an attack vector because the user needs to be logged in to do something like that. It would also be futile for an attacker to worry about the password strength as he can easily remember a strong password too.
**We are not currently planning to solve this 'problem'** because it would force us to send clear text passwords over the wire.
