### ISSUE TITLE
DDerl rpc connections to sibling cluster node does not work

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#368]
Cannot connect from one cpro node to another cluster member via RPC.

**Comment by shamis** [comment]
When connecting over RPC no long lasting process is started. Seco registers the pid of the `rpc:call` as the pid of the signing in process. But this process dies when the rpc call is complete. This will result in the pid being cleaned up from the seco table as this pid was being monitored. Since this pid not there in the seco the next step of the authentication cannot be processed as the seco context is completely lost. For local rpc connection the erlimem session process is used to register which lives as long as the session and for TCP connection imem_server starts are receive block.
cc @acautin @c-bik

**Comment by c-bik** [comment]
erlimem_session PID need to be considered for Seco/SKey instead of transient internal RPC PID

**Comment by shamis** [comment]
Completely removed rpc interface https://github.com/K2InformaticsGmbH/dderl/pull/457

**Comment by acautin** [comment]
Closing as rpc support was removed.
