### ISSUE TITLE
Browse data improvements for directory browsing.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#506]
As dderl should also support the exploration of directories and files, we should support the replacement of the current table content by the content of the new opened window, avoiding having too many open when trying to locate files deep in the tree.

On Browse Data dderl should check for especial browse conditions depending on the row context similar to how the current views are handled but for arbitrary cases defined by the user.

Add a new menu entry command to redefine the default browse data for a column, this command should open a interface to allow to define how browse data will behave, allow to define a view and the list of parameters with name and value. Values for this parameters could also be defined as variables pointing to the data in the current row.

When setting the view name it should be possible to search for its definition to populate the list of parameters needed for binding.

**Comment by stoch** [comment]
I want to use this parameterized view:

![image](https://user-images.githubusercontent.com/1941407/39261315-60cca296-48bc-11e8-9e82-990fafe0739c.png)

But it seems that the view is not found (and the view name input box is far to small):

![image](https://user-images.githubusercontent.com/1941407/39261437-bd45996a-48bc-11e8-96d2-e607cfdae24c.png)

ddView and ddCmd have the correct name, after removing an unwanted trailing space character (maybe we should reject View safe if trim(name) is not matching the name )

![image](https://user-images.githubusercontent.com/1941407/39261242-377b7228-48bc-11e8-925f-95116618cb97.png)

Defining the view .dual worked because it has no parameters.

Defining the view with .dummy does not work with its simple SQL

SELECT
    :SQLT_STR_DUMMY
FROM
    dual

**Comment by acautin** [comment]
@stoch Realized I am only searching for views of the current user, a workaround (if possible) would be to change the ownership of the views to system.

**Comment by acautin** [comment]
Also follow up question is: what is the expected result when there are multiple views defined with the same name ?
